# Generated by Django 6.0.2 on 2026-03-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='employee_image')),
            ],
        ),
    ]
